package P21_30;

import java.util.ArrayList;

/**
 * Author: DarrenZeng
 * Date: 2015-12-17
 */
/*
    =====Project Euler 29=====

    Consider all integer combinations of ab for 2 ¡Ü a ¡Ü 5 and 2 ¡Ü b ¡Ü 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ¡Ü a ¡Ü 100 and 2 ¡Ü b ¡Ü 100?
*/
public class P29 {
    public static int getTotal(int number) {
        ArrayList<String> list = new ArrayList<String>();
        for (int i = 2; i <= number; i++) {
            for (int j = 2; j <= number; j++) {
                String result = getPow(i, j);
                if (!list.contains(result))
                    list.add(result);
            }
        }
        return list.size();
    }

    private static String getPow(int a, int b) {
        ArrayList<Integer> result = new ArrayList<Integer>();

        result.add(0, 1);
        for (int i = 1; i <= b; i++) {
            int carryBit = 0;
            for (int j = 0; j < result.size(); j++) {
                int tempResult = result.get(j) * a + carryBit;
                result.set(j, tempResult % 10);
                carryBit = tempResult / 10;
            }

            if (carryBit > 0) {
                result.add(result.size(), carryBit);
            }
        }

        String str = "";
        for (int i = result.size() - 1; i >= 0; i--) {
            str += result.get(i);
        }
        return str;
    }
}
