package P0_10;

/**
 * Author: DarrenZeng
 * Date: 2015-11-27
 */
/*
    =====Project Euler 2=====

    Each new term in the Fibonacci sequence
	is generated by adding the previous two terms. By starting with 1 and
	2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do
	not exceed four million, find the sum of the even-valued terms.
 */
public class P2 {
    public static long getSum(int number) {
        long sum = 0;
        int n = 2;
        int fibN = GetFib(n);
        while (fibN <= number) {
            if (fibN % 2 == 0)
                sum += fibN;
            n++;
            fibN = GetFib(n);
        }
        return sum;
    }

    /* 此处z一开始等于偶数，x和y一开始都等于奇数，而后来x和y都是由奇数+z得到，所以x和y一直是奇数。而z是x+y得到，所以z一直是存放的偶数。*/
    public static long getSumBetter(int number) {
        int x = 1, y = 1;
        int z = x + y;
        long sum = 0;
        while (z < number) {
            sum += z;
            x = y + z;
            y = z + x;
            z = x + y;
        }
        return sum;
    }

    private static int GetFib(int n) {
        if (n == 1 || n == 2)
            return n;
        return GetFib(n - 1) + GetFib(n - 2);
    }
}
